/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : BetaSoft
 */


extern BYTE StopBit,PatternBit,RowBit;
extern BOOL Loop,Paused;

extern struct Module *Mod;
extern struct FileRequester *FileReq;

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_Module                              0
#define GD_Play                                1
#define GD_Stop                                2
#define GD_Quit                                3
#define GD_Pause                               4
#define GD_Load                                5
#define GD_Fade                                6
#define GD_Length                              7
#define GD_Pos                                 8
#define GD_Pat                                 9
#define GD_Row                                 10
#define GD_Loop                                11

#define GDX_Module                             0
#define GDX_Play                               1
#define GDX_Stop                               2
#define GDX_Quit                               3
#define GDX_Pause                              4
#define GDX_Load                               5
#define GDX_Fade                               6
#define GDX_Length                             7
#define GDX_Pos                                8
#define GDX_Pat                                9
#define GDX_Row                                10
#define GDX_Loop                               11

#define Control_CNT 12

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;
extern struct Library *DOSBase;
extern struct Library *AslBase;
extern struct Library *PTReplayBase;
extern struct Library *DiskfontBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *ControlWnd;
extern struct Gadget        *ControlGList;
extern struct IntuiMessage   ControlMsg;
extern struct Gadget        *ControlGadgets[11];
extern UWORD                 ControlLeft;
extern UWORD                 ControlTop;
extern UWORD                 ControlWidth;
extern UWORD                 ControlHeight;
extern UBYTE                *ControlWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *ControlFont;
extern struct GfxBase       *GfxBase;
extern UWORD                 ControlGTypes[];
extern struct NewGadget      ControlNGad[];
extern ULONG                 ControlGTags[];

extern int PlayClicked( void );
extern int StopClicked( void );
extern int QuitClicked( void );
extern int PauseClicked( void );
extern int LoadClicked( void );
extern int FadeClicked( void );
extern int LoopClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void ControlRender( void );
extern int HandleControlIDCMP( void );
extern int ControlCloseWindow( void );
extern int ControlVanillaKey( void );
extern int OpenControlWindow( void );
extern void CloseControlWindow( void );
