/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : BetaSoft
 */


extern BYTE StopBit,PatternBit,RowBit;
extern BOOL Loop,Paused;

extern struct Module *Mod;
extern struct FileRequester *FileReq;

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

enum GD {
    GD_Module = 0,
    GD_Loop,
    GD_Play,
    GD_Stop,
    GD_Quit,
    GD_Pause,
    GD_Load,
    GD_Fade,
    GD_Length,
    GD_Pos,
    GD_Pat,
    GD_Row,
    GD_RData,
    GD_COUNT
};


extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;
extern struct Library *DOSBase;
extern struct Library *AslBase;
extern struct Library *PTReplayBase;
extern struct Library *DiskfontBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *ControlWnd;
extern struct Gadget        *ControlGList;
extern struct IntuiMessage   ControlMsg;
extern struct Gadget        *ControlGadgets[GD_COUNT];
extern UWORD                 ControlLeft;
extern UWORD                 ControlTop;
extern UWORD                 ControlWidth;
extern UWORD                 ControlHeight;
extern UBYTE                *ControlWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *ControlFont;
extern struct GfxBase       *GfxBase;
extern UWORD                 ControlGTypes[];
extern struct NewGadget      ControlNGad[];
extern ULONG                 ControlGTags[];

extern int PlayClicked( void );
extern int StopClicked( void );
extern int QuitClicked( void );
extern int PauseClicked( void );
extern int LoadClicked( void );
extern int FadeClicked( void );
extern int LoopClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern void ControlRender( void );
extern int HandleControlIDCMP( void );
extern int ControlCloseWindow( void );
extern int ControlVanillaKey( void );
extern int OpenControlWindow( void );
extern void CloseControlWindow( void );
