#ifndef INLINE4_PTPLAY_H
#define INLINE4_PTPLAY_H

/*
** This file was auto generated by idltool 51.8.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

/* Inline macros for Interface "main" */
#define PtInit(buf, bufsize, frequency, modtype) IPtPlay->PtInit(buf, bufsize, frequency, modtype) 
#define PtRender(mod, destbuf1, destbuf2, bufmodulo, numsp, scale, depth, channels) IPtPlay->PtRender(mod, destbuf1, destbuf2, bufmodulo, numsp, scale, depth, channels) 
#define PtTest(filename, buf, bufsize) IPtPlay->PtTest(filename, buf, bufsize) 
#define PtCleanup(mod) IPtPlay->PtCleanup(mod) 
#define PtSetAttrs(mod, taglist) IPtPlay->PtSetAttrs(mod, taglist) 
#define PtGetAttr(mod, tagitem, storagePtr) IPtPlay->PtGetAttr(mod, tagitem, storagePtr) 
#define PtSeek(mod, time) IPtPlay->PtSeek(mod, time) 

#endif /* INLINE4_PTPLAY_H */
